# Generated by Django 3.2.9 on 2022-05-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mgt_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'regions'},
        ),
    ]
